### ISSUE TITLE
Can't parse poc error: : no template name field provided

### ISSUE THREAD

**Issue by TheTh1nk3r** [WAY29/pocV#4] opened 2022-02-25 10:09 UTC
![image](https://user-images.githubusercontent.com/42456962/155696449-c693dd6e-38b0-41f0-b138-4dcc76aa8efa.png)
![image](https://user-images.githubusercontent.com/42456962/155696477-b12111f5-bff4-4647-bcca-9e94aa688307.png)

**Comment by WAY29** [comment] 2022-02-25 10:23
I failed to reproduce locally. Can you add the -- debug option to give me more output?

**Comment by TheTh1nk3r** [comment] 2022-02-25 10:51
报错
![image](https://user-images.githubusercontent.com/42456962/155702775-8a3a2ed7-40f5-4840-9e5e-5b3d35e4e80c.png)

[18:49] ERROR Raw Error: Can't parse poc error: : no template name field provided
github.com/WAY29/pocV/internal/common/load.LoadPocs.func1
        E:/code/go/pocV/pocV-main/internal/common/load/load.go:69
github.com/WAY29/pocV/internal/common/load.LoadPocs
        E:/code/go/pocV/pocV-main/internal/common/load/load.go:91
main.cmdRun.func1
        E:/code/go/pocV/pocV-main/cmd/pocV/pocV.go:78
github.com/jawher/mow.cli/internal/flow.(*Step).callDo
        E:/Program Files(x86)/gopath/pkg/mod/github.com/jawher/mow.cli@v1.2.0/internal/flow/flow.go:55
github.com/jawher/mow.cli/internal/flow.(*Step).Run
        E:/Program Files(x86)/gopath/pkg/mod/github.com/jawher/mow.cli@v1.2.0/internal/flow/flow.go:25
github.com/jawher/mow.cli/internal/flow.(*Step).Run
        E:/Program Files(x86)/gopath/pkg/mod/github.com/jawher/mow.cli@v1.2.0/internal/flow/flow.go:29
github.com/jawher/mow.cli/internal/flow.(*Step).Run
        E:/Program Files(x86)/gopath/pkg/mod/github.com/jawher/mow.cli@v1.2.0/internal/flow/flow.go:29
github.com/jawher/mow.cli/internal/flow.(*Step).Run
        E:/Program Files(x86)/gopath/pkg/mod/github.com/jawher/mow.cli@v1.2.0/internal/flow/flow.go:29
github.com/jawher/mow%2ecli.(*Cmd).parse
        E:/Program Files(x86)/gopath/pkg/mod/github.com/jawher/mow.cli@v1.2.0/commands.go:693
github.com/jawher/mow%2ecli.(*Cmd).parse
        E:/Program Files(x86)/gopath/pkg/mod/github.com/jawher/mow.cli@v1.2.0/commands.go:707
github.com/jawher/mow%2ecli.(*Cli).parse
        E:/Program Files(x86)/gopath/pkg/mod/github.com/jawher/mow.cli@v1.2.0/cli.go:76   
github.com/jawher/mow%2ecli.(*Cli).Run
        E:/Program Files(x86)/gopath/pkg/mod/github.com/jawher/mow.cli@v1.2.0/cli.go:105  
main.main
        E:/code/go/pocV/pocV-main/cmd/pocV/pocV.go:134
[18:49] DEBUG Load poc file: pocs\xray\weiphp-sql.yml
[18:49] ERROR Raw Error: Can't parse poc error: : no template name field provided
github.com/WAY29/pocV/internal/common/load.LoadPocs.func1
        E:/code/go/pocV/pocV-main/internal/common/load/load.go:69
github.com/WAY29/pocV/internal/common/load.LoadPocs
        E:/code/go/pocV/pocV-main/internal/common/load/load.go:91
main.cmdRun.func1
        E:/code/go/pocV/pocV-main/cmd/pocV/pocV.go:78
github.com/jawher/mow.cli/internal/flow.(*Step).callDo
        E:/Program Files(x86)/gopath/pkg/mod/github.com/jawher/mow.cli@v1.2.0/internal/flow/flow.go:55
github.com/jawher/mow.cli/internal/flow.(*Step).Run
        E:/Program Files(x86)/gopath/pkg/mod/github.com/jawher/mow.cli@v1.2.0/internal/flow/flow.go:25
github.com/jawher/mow.cli/internal/flow.(*Step).Run
        E:/Program Files(x86)/gopath/pkg/mod/github.com/jawher/mow.cli@v1.2.0/internal/flow/flow.go:29
github.com/jawher/mow.cli/internal/flow.(*Step).Run
        E:/Program Files(x86)/gopath/pkg/mod/github.com/jawher/mow.cli@v1.2.0/internal/flow/flow.go:29
github.com/jawher/mow.cli/internal/flow.(*Step).Run
        E:/Program Files(x86)/gopath/pkg/mod/github.com/jawher/mow.cli@v1.2.0/internal/flow/flow.go:29
github.com/jawher/mow%2ecli.(*Cmd).parse
        E:/Program Files(x86)/gopath/pkg/mod/github.com/jawher/mow.cli@v1.2.0/commands.go:693
github.com/jawher/mow%2ecli.(*Cmd).parse
        E:/Program Files(x86)/gopath/pkg/mod/github.com/jawher/mow.cli@v1.2.0/commands.go:707
github.com/jawher/mow%2ecli.(*Cli).parse
        E:/Program Files(x86)/gopath/pkg/mod/github.com/jawher/mow.cli@v1.2.0/cli.go:76
github.com/jawher/mow%2ecli.(*Cli).Run
        E:/Program Files(x86)/gopath/pkg/mod/github.com/jawher/mow.cli@v1.2.0/cli.go:105
main.main
        E:/code/go/pocV/pocV-main/cmd/pocV/pocV.go:134
[18:49]  INFO Load [0] xray poc(s), [0] nuclei poc(s)

**Comment by WAY29** [comment] 2022-02-25 13:45
The problem is shiziyu-cms-apicontroller-sqli.yml cannot be successfully resolved to a PoC of xray type, but an error occurred when trying to resolve it to a PoC of nuclei type. There is no problem when I load this POC individually in the local test. Can you put your shiziyu-cms-apicontroller-sqli.yml here？

**Comment by WAY29** [comment] 2022-02-26 07:46
Is Your Xray Poc v2?

**Comment by WAY29** [comment] 2022-02-27 01:52
The bug has been tested in the new version and has not been successfully reproduced, so close the issue. If there are any more problems, please re-issue.

**Closed as completed by WAY29** 2022-02-27 01:52 UTC
